---
title: "Balance checks"
output: html_notebook
---

```{r setup}
library(tidyverse)
library(interactions)
library(stargazer)
library(fastDummies)
library(cobalt)
#full.data <- read.csv("cleaned data full all years_v2.csv")

full.data <- read.csv("coefs with city covariates cleaned.csv")
#absentee <- read.csv("absentee coefficients.csv")
#absentee <- absentee %>% dplyr::select(pct.absentee, city_id_year)
#full.data <- merge(full.data, absentee, by = "city_id_year")

#Note: Missing cities are manually added to full.data file

full.data <- full.data %>% mutate(presidential = ifelse(year.x == 2004 | year.x == 2008 | year.x == 2012, 1, 0))
full.data <- full.data %>% mutate(known.opp.mayor = ifelse(is.na(opp_mayor1) == T, 0, ifelse(opp_mayor1==1, 1,0)))
full.data <- full.data %>% mutate(appointed.exec = ifelse(is.na(cancel.year)==T, 0, ifelse(year.x >= cancel.year, 1, 0)))
full.data <- full.data %>% rename(turnout.coef = turnout)

full.data <- full.data %>% mutate(years.with.elections = ifelse(is.na(cancel.year)==T, year.x-1996, ifelse(year.x - cancel.year < 0, year.x - 1996, cancel.year - 1996))) #This gives a measure of early vs late vs. control; 1996 bc this is when local elections first took place 

full.data <- full.data %>% mutate(years.post.treatment = ifelse(is.na(cancel.year)==T, 0, ifelse(year.x - cancel.year < 0, 0, year.x - cancel.year)))
full.data <- full.data %>% mutate(years.post.treatment = ifelse(is.na(cancel.year)==F & cancel.year == 2007 & year.x ==2007, 1, years.post.treatment)) #This codes cancelations in 2007 and 2011 as 1 for those years, since elections take place at year-end.
full.data <- full.data %>% mutate(years.post.treatment = ifelse(is.na(cancel.year)==F & cancel.year == 2011 & year.x ==2011, 1, years.post.treatment)) #This codes cancelations in 2007 and 2011 as 1 for those years, since elections take place at year-end.

full.data <- full.data %>% mutate(treated.post.treatment = ifelse(is.na(cancel.year)==T, 0, ifelse(year.x - cancel.year < 0, 0, 1)))
full.data <- full.data %>% mutate(treated.post.treatment = ifelse(is.na(cancel.year)==F & cancel.year == 2007 & year.x ==2007, 1, treated.post.treatment)) #This codes cancelations in 2007 and 2011 as 1 for those years, since elections take place at year-end.
full.data <- full.data %>% mutate(treated.post.treatment = ifelse(is.na(cancel.year)==F & cancel.year == 2011 & year.x ==2011, 1, treated.post.treatment)) #This codes cancelations in 2007 and 2011 as 1 for those years, since elections take place at year-end.


full.data <- full.data %>% mutate(years.under.appt = ifelse(is.na(cancel.year) == T, 0, ifelse(year.x - cancel.year < 0, 0, ifelse(year.x == 2007 | year.x == 2011 & year.x == cancel.year, 1, year.x - cancel.year))))

full.data <- full.data %>% mutate(city_id_factor = as.factor(city_id))


full.data <- full.data %>% mutate(treatment.group = ifelse(is.na(cancel.year)==F, 1, 0))

full.data <- full.data %>% mutate(control = ifelse(is.na(cancel.year)==T, 1, 0))
full.data <- full.data %>% mutate(early.treated = ifelse(is.na(cancel.year)==F & cancel.year <= 2007, 1, 0))
full.data <- full.data %>% mutate(late.treated = ifelse(is.na(cancel.year)==F & cancel.year > 2007, 1, 0))


full.data <- full.data %>% mutate(years.under.regime = ifelse(appointed.exec == 0, year.x - 2000, year.x - cancel.year))

##Dummies for ethnic categorical

full.data <- dummy_cols(full.data, select_columns = "ethnic.categorical")
full.data <- full.data %>% rename(majority.russian.republic = ethnic.categorical_Majority_Russian_republic)
full.data <- full.data %>% rename(majority.minority.republic = `ethnic.categorical_Majority-minority_republic`)
```

```{r}
# Multiple plot function
#
# ggplot objects can be passed in ..., or to plotlist (as a list of ggplot objects)
# - cols:   Number of columns in layout
# - layout: A matrix specifying the layout. If present, 'cols' is ignored.
#
# If the layout is something like matrix(c(1,2,3,3), nrow=2, byrow=TRUE),
# then plot 1 will go in the upper left, 2 will go in the upper right, and
# 3 will go all the way across the bottom.
#
multiplot <- function(..., plotlist=NULL, file, cols=1, layout=NULL) {
  library(grid)

  # Make a list from the ... arguments and plotlist
  plots <- c(list(...), plotlist)

  numPlots = length(plots)

  # If layout is NULL, then use 'cols' to determine layout
  if (is.null(layout)) {
    # Make the panel
    # ncol: Number of columns of plots
    # nrow: Number of rows needed, calculated from # of cols
    layout <- matrix(seq(1, cols * ceiling(numPlots/cols)),
                    ncol = cols, nrow = ceiling(numPlots/cols))
  }

 if (numPlots==1) {
    print(plots[[1]])

  } else {
    # Set up the page
    grid.newpage()
    pushViewport(viewport(layout = grid.layout(nrow(layout), ncol(layout))))

    # Make each plot, in the correct location
    for (i in 1:numPlots) {
      # Get the i,j matrix positions of the regions that contain this subplot
      matchidx <- as.data.frame(which(layout == i, arr.ind = TRUE))

      print(plots[[i]], vp = viewport(layout.pos.row = matchidx$row,
                                      layout.pos.col = matchidx$col))
    }
  }
}
```

```{r}
covariates <- full.data %>% filter(year.x == 2003 | year.x == 2004) %>% select(urgov, mayor.tenure, lnAvgSalary, dem, comp.scale2, known.opp.mayor, turnout.coef, ur.voteshare, treatment.group, margin)

covariates$p.score2 <- glm(treatment.group ~ urgov + mayor.tenure + lnAvgSalary + dem + comp.scale2 + known.opp.mayor + turnout.coef + ur.voteshare, 
                        data = covariates, family = "binomial")$fitted.values

bal.tab(treatment.group ~ covariates, data = covariates,
        disp = c("means", "sds"), un = TRUE, 
        stats = c("mean.diffs", "variance.ratios"))

bal.gov <- bal.plot(covariates, var.name = "urgov", treat = covariates$treatment.group)
bal.margin <- bal.plot(covariates, var.name = "margin", treat = covariates$treatment.group)
bal.sal <- bal.plot(covariates, var.name = "lnAvgSalary", treat = covariates$treatment.group)
bal.dem <- bal.plot(covariates, var.name = "dem", treat = covariates$treatment.group)
bal.comp <- bal.plot(covariates, var.name = "comp.scale2", treat = covariates$treatment.group)
bal.tc <- bal.plot(covariates, var.name = "turnout.coef", treat = covariates$treatment.group)
bal.oppmayor <- bal.plot(covariates, var.name = "known.opp.mayor", treat = covariates$treatment.group)
bal.ur <- bal.plot(covariates, var.name = "ur.voteshare", treat = covariates$treatment.group)

bal.gov
bal.margin
bal.sal
bal.dem
bal.comp
bal.tc
bal.oppmayor
bal.ur

```


```{r}
plots.balanced <- multiplot(bal.gov, bal.oppmayor, bal.sal, bal.ur, cols = 2)

plots.unbalanced <- multiplot(bal.margin, bal.dem, bal.comp, bal.tc, cols = 2)

```


